name: weight_scale_app
description: A Flutter application for weight scale with Bluetooth and Google Sheets integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bluetooth_serial: ^0.4.0
  http: ^0.13.5
  fl_chart: ^0.55.0
  shared_preferences: ^2.0.15
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
